import React,{useEffect,useMemo,useRef,useState}from'react';import{Pause,Play,Volume2,VolumeX,X}from'lucide-react';
export type PreviewClip={id:string;kind?:string;track?:string;path?:string;start:number;duration:number;name?:string;volume?:number};export type PreviewTimeline={duration:number;items:PreviewClip[]};
const API='http://127.0.0.1:18765';
function mediaUrl(path?:string){return path?`${API}/file?path=${encodeURIComponent(path)}`:''}
function fmt(t:number){const s=Math.max(0,Math.floor(t));return`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
export default function PreviewPlayer({timeline,onClose}:{timeline:PreviewTimeline;onClose:()=>void}){const[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[muted,setMuted]=useState(false),videoRef=useRef<HTMLVideoElement>(null),audioRefs=useRef<Record<string,HTMLAudioElement>>({});const active=useMemo(()=>timeline.items.filter(x=>time>=x.start&&time<x.start+x.duration),[timeline.items,time]);const visual=active.find(x=>x.kind==='video'||x.track==='video'&&x.path);const image=active.find(x=>x.kind==='image'&&x.path);const audio=active.filter(x=>x.track==='voice'||x.track==='music');
useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setTime(t=>{const n=t+.05;return n>=timeline.duration?(setPlaying(false),timeline.duration):n}),50);return()=>clearInterval(id)},[playing,timeline.duration]);
useEffect(()=>{const v=videoRef.current;if(!v||!visual?.path)return;const local=Math.max(0,time-visual.start);if(Math.abs(v.currentTime-local)>.15)v.currentTime=local;if(playing)v.play().catch(()=>{});else v.pause()},[time,playing,visual?.path,visual?.start]);
useEffect(()=>{audio.forEach(item=>{const el=audioRefs.current[item.id];if(!el||!item.path)return;const local=Math.max(0,time-item.start);if(Math.abs(el.currentTime-local)>.15)el.currentTime=local;el.volume=Math.max(0,Math.min(1,item.volume??1));el.muted=muted;if(playing)el.play().catch(()=>{});else el.pause()});Object.keys(audioRefs.current).forEach(id=>{if(!audio.some(x=>x.id===id))audioRefs.current[id].pause()})},[time,playing,muted,audio]);
useEffect(()=>{if(time>=timeline.duration)setPlaying(false)},[time,timeline.duration]);return <div className="preview-overlay"><div className="preview-window"><div className="preview-head"><strong>Предпросмотр проекта</strong><button className="ghost"onClick={onClose}><X size={15}/></button></div><div className="preview-stage">{visual?.path?<video ref={videoRef} src={mediaUrl(visual.path)} muted={muted} playsInline/>:image?.path?<img src={mediaUrl(image.path)} alt="Предпросмотр"/>:<div className="preview-placeholder">На текущем времени нет визуального клипа</div>}{audio.map(item=>item.path?<audio key={item.id} ref={el=>{if(el)audioRefs.current[item.id]=el;else delete audioRefs.current[item.id]}} src={mediaUrl(item.path)} preload="auto"/>:null)}</div><div className="preview-controls"><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><span className="preview-time">{fmt(time)} / {fmt(timeline.duration)}</span><div className="preview-scrubber"><input type="range"min="0"max={Math.max(.01,timeline.duration)}step=".01"value={time}onChange={e=>setTime(Number(e.target.value))}/></div><button onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX size={15}/>:<Volume2 size={15}/>}</button></div>{audio.length>0&&<div style={{padding:'0 15px 12px',color:'#6f7785',fontSize:10}}>Аудио-клипов в проекте: {audio.length}</div>}</div></div>}
