import React,{useEffect,useMemo,useRef,useState}from'react';import{Pause,Play,X,Volume2,VolumeX}from'lucide-react';
export type PreviewItem={id:string;kind?:string;track?:string;name?:string;path?:string;duration:number;start:number};export type PreviewTimeline={duration:number;fps:number;items:PreviewItem[]};
const API='http://127.0.0.1:18765';
function assetUrl(path?:string){return path?`${API}/file?path=${encodeURIComponent(path)}`:''}
export default function PreviewPlayer({timeline,onClose}:{timeline:PreviewTimeline;onClose:()=>void}){const[time,setTime]=useState(0),[playing,setPlaying]=useState(true),[muted,setMuted]=useState(false),videoRef=useRef<HTMLVideoElement>(null),last=useRef(performance.now());const active=useMemo(()=>timeline.items.filter(x=>time>=x.start&&time<x.start+x.duration),[timeline.items,time]);
useEffect(()=>{last.current=performance.now();let raf=0;const tick=(now:number)=>{if(playing){const delta=(now-last.current)/1000;setTime(t=>{const n=t+delta;return n>=timeline.duration?0:n})}last.current=now;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing,timeline.duration]);
const visual=active.find(x=>x.track==='video'||x.kind==='image'||x.kind==='video');const audio=active.find(x=>x.track==='voice'||x.track==='music'||x.kind==='audio'||x.kind==='voice'||x.kind==='music');const src=assetUrl(visual?.path);useEffect(()=>{if(videoRef.current){videoRef.current.muted=muted;if(playing)videoRef.current.play().catch(()=>{});else videoRef.current.pause()}},[playing,muted,src]);
function seek(v:number){setTime(Math.max(0,Math.min(timeline.duration,v)))}return <div className="preview-overlay"role="dialog"aria-label="Предпросмотр проекта"><div className="preview-window"><div className="preview-head"><div><span className="eyebrow">ПРЕДПРОСМОТР</span><strong>Текущий проект</strong></div><button className="ghost"onClick={onClose}><X size={16}/></button></div><div className="preview-stage">{visual?.kind==='video'&&src?<video ref={videoRef}src={src}playsInline/>:visual?.path?<img src={src}alt={visual.name||'Кадр проекта'}/>:<div className="preview-placeholder">{audio?`▶ ${audio.name||'Аудио'}`:'Добавьте материалы в Timeline'}</div>}<div className="preview-badge">{active.length?active.map(x=>x.name||x.kind).join(' · '):'Пустая сцена'}</div></div><div className="preview-controls"><button onClick={()=>setPlaying(v=>!v)}title={playing?'Пауза':'Воспроизведение'}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><span className="preview-time">{fmt(time)} / {fmt(timeline.duration)}</span><div className="preview-scrubber"><input type="range"min="0"max={Math.max(.01,timeline.duration)}step="0.01"value={time}onChange={e=>seek(Number(e.target.value))}/></div><button onClick={()=>setMuted(v=>!v)}title={muted?'Включить звук':'Выключить звук'}>{muted?<VolumeX size={15}/>:<Volume2 size={15}/>}</button></div></div></div>}
function fmt(v:number){const m=Math.floor(v/60);const s=Math.floor(v%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
